version: '3.8'

services:
  mysql-container:
    image: mysql:5.7
    container_name: slcatering_mariadb
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_PASS}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: slcatering_be
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql-container

volumes:
  data: