version: '3.8'

services:
  slcatering:
    container_name: slcatering_be
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal