# Generated by Django 3.1.3 on 2024-06-27 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('imageLink', models.CharField(default='https://media.istockphoto.com/id/1409329028/vector/no-picture-available-placeholder-thumbnail-icon-illustration-design.jpg?s=612x612&w=0&k=20&c=_zOuJu755g2eEUioiOUdz_mHKJQJn-tDgIAhQzyeKUQ=', max_length=255)),
                ('price', models.IntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('store_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VariantCaterings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=255)),
                ('additional_price', models.IntegerField()),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_variants', to='api.catering')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField()),
                ('quantity', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=255)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering', to='api.catering')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to='api.user')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='api.variantcaterings')),
            ],
        ),
        migrations.AddField(
            model_name='catering',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to='api.user'),
        ),
    ]
