# Generated by Django 3.1.3 on 2024-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duitku_reference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
