# Generated by Django 3.1.3 on 2024-09-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_duitku_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='duitku_reference',
            new_name='publisher_order_id',
        ),
    ]
