# Generated by Django 3.1.3 on 2024-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240921_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='catering',
            name='weightPortion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
